baseurl = "/"
publishDir = "docs"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "William E Fondrie"
theme = "hugo-marmot"
googleAnalytics = "UA-78640578-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.qmd$", "\\.ipynb$", "\\.py$"]
footnotereturnlinkcontents = "↩"

[author]
  name = "William E Fondrie"

[blackfriday]
  hrefTargetBlank = true

[permalinks]
  post = "/:year/:month/:title/"

[params]
  name = "William E Fondrie"
  description = "Data Science @ Talus Bio"
  footer = """\
    &copy; [William E. Fondrie](https://willfondrie.com) 2018--{Year}\
    """
  buyMeACoffee = "wfondrie"

  [[params.social]]
    name = "github"
    url = "https://github.com/wfondrie"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/wfondrie"

  [[params.social]]
    name = "mastodon"
    url = "https://genomic.social/@wfondrie"

  [[params.social]]
    name = "Scholar"
    url = "https://scholar.google.com/citations?user=sagQuRkAAAAJ"

[menus]
  [[menu.main]]
    name = "Me"
    url = "/"
    weight = 1

 [[menu.main]]
    name = "Posts"
    url = "post/"
    weight = 2

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = false
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    style = 'monokai'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
